run: build
	./opt_0.out
build: HashTableTest.cpp
	g++ HashTableTest.cpp -o opt_0.out
o1: HashTableTest.cpp
	g++ HashTableTest.cpp -O1 -o opt_1.out
o2: HashTableTest.cpp
	g++ HashTableTest.cpp -O2 -o opt_2.out
o3: HashTableTest.cpp
	g++ HashTableTest.cpp -O3 -o opt_3.out


